Repository SWE40001-SEPA-Group-42/on-demand-teleheath-platform, pull requests merged in 2022-11, with the labels that each got.

#21 frontend/dashboard-doctor-table
  backend/server/controllers/dashboardController.js
  backend/server/controllers/patientController.js
  backend/server/middleware/validatorMiddleware.js
  backend/server/routes/dashboardRoutes.js
  backend/server/routes/patientRoutes.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Dashboard/Dashboard.tsx
  frontend/src/components/Dashboard/Profiles/PatientProfile.tsx
  frontend/src/components/Dashboard/Table/DoctorTable.tsx
  frontend/src/components/Dashboard/Table/PatientTable.tsx
  frontend/src/components/Dashboard/Table/uuid.d.ts
  frontend/src/components/shared/LayoutsWithNavbar.tsx
  frontend/src/components/shared/Navbar.tsx
  frontend/src/containers/Patient/PatientUpdateProfile.tsx
  frontend/src/redux/Appointment/appointmentsSlice.ts
  frontend/src/redux/Doctor/doctorsSlice.ts
  frontend/src/redux/Doctor/filterSlice.ts
  frontend/src/redux/Patient/patientsSlice.ts
  frontend/src/redux/store.ts
  frontend/src/styles/App.css
  frontend/src/types/Appointment.ts
  frontend/src/types/Clinic.ts
  frontend/src/types/Doctor.ts
  frontend/src/types/Patient.ts
  package-lock.json
  package.json
Labels: needs review

#23 Backend/update tests
  backend/README.md
  backend/server/models/patient.js
  backend/server/tests/endpoints.test.js
  backend/server/tests/init.js
Labels: bug

#24 Frontend/SEPAB-82-video-call-UI
  frontend/README.md
  frontend/src/components/LandingPage/LandingPage.tsx
  frontend/src/components/routing/Routing.tsx
  frontend/src/containers/VideoCall/ConsultationRoom.jsx
  frontend/src/containers/VideoCall/CreateRoom.jsx
  frontend/src/containers/VideoCall/JoinCall.jsx
  frontend/src/containers/VideoCall/Room.jsx
  frontend/src/containers/VideoCall/VideoCallControls.tsx
  frontend/src/styles/App.css
  frontend/src/styles/components/containers.css
  frontend/src/styles/components/index.css
  frontend/src/styles/components/videoCall.css
  frontend/tailwind.config.js
Labels: enhancement
